### ISSUE TITLE
Output failing file on syntax error

### ISSUE THREAD

**Issue by umulmrum** [sensiolabs-de/deprecation-detector#10]
If a source file fails to compile, the detector aborts with an error message like this:

[PhpParser\Error]                        
Syntax error, unexpected EOF on line 11 

In large projects there might be abandoned files that don't even compile, so I think it would be great to have the path of the file that fails.

Perhaps it makes sense to continue the detection run even if some files fail.

**Comment by slde-gorillaman** [comment]
Output has been corrected by #15, however execution is still halted

**Comment by slde-gorillaman** [comment]
#7 describes to blacklist files and folders. Maybe this can be used to exclude files that contain parser errors

**Comment by slde-gorillaman** [comment]
In order to continue execution, the \SensioLabs\DeprecationDetector\RuleSet\Traverser::traverse method could be enhanced with a third optional parameter ```$exclude = array()``` which could hold paths to directories or files to be excluded in traversing the rule set.

As far as I can tell, this is the only possible point in code to include skipping of "broken" files or folders

**Comment by derrabus** [comment]
Instead of maintaining a list of broken files, wouldn't it make more sense to catch the exception, report the file to be broken and skip it?

**Comment by slde-gorillaman** [comment]
That would be the optimal way, however the current setup does not allow to catch the exception, and continue traversing on an application level. The catch would have to be implemented in the Traverser, which would have to report back to the application with a list of exceptions for the console output.
Imho, that would be a rather ugly way.

As a quick thought, the Traverser could collect exceptions, continue working and the application could call a getter to print the exceptions.

**Comment by slde-gorillaman** [comment]
Sorry, I have been looking at the ruleset generation,  not the analysis of the own code.
But we have here the same problem (previous comment is wrong), when calling the ParsedPhpFileFinder::getIterator we get the parser errors, but I cannot figure out a clean way to report those errors back to the caller without interrupting execution. I'll try out collecting them and have the caller ask for them.

**Comment by slde-gorillaman** [comment]
The PR #30 should fix this issue now
