### ISSUE TITLE
Missing file vendor/autoload.php.   But its there ....

### ISSUE THREAD

**Issue by whitewhidow** [sensiolabs-de/deprecation-detector#102]
I keep getting 

    Missing file vendor/autoload.php. Please run "composer install"!

But the file is defenantly there ...

```
[sam:~/git/PosBranch] more-deprecations+* ± deprecation-detector check src/ vendor/
Missing file vendor/autoload.php. Please run "composer install"!

[sam:~/git/PosBranch] more-deprecations+* ± ls -la vendor/ | grep auto
-rw-r--r--  1 sam sam  183 Feb  2 14:22 autoload.php
```

Im sure its something wrong on my end, but i cant figure it out.

**Comment by xabbuh** [comment]
How did you get the `deprecation-detector` file to the same directory as the `src` and `vendor` directories? Usually it's located in the `bin` subdirectory. Moving the file will make it look for the autoloading file in the wrong directory.

**Comment by whitewhidow** [comment]
yep, had a brainfart, i had actually installed it globally, so the paths didnt make sense

thx
