### ISSUE TITLE
Upgrade to nikic/php-parser 2.0

### ISSUE THREAD

**Issue by theofidry** [sensiolabs-de/deprecation-detector#103]
Would it be possible to do it? The 2.0 has been stable for some time now and is PHP7 compatible unlike the 1.0.

**Comment by MarvinKlemp** [comment]
I'll check it out this weekend

**Comment by theofidry** [comment]
Cheers

**Comment by MarvinKlemp** [comment]
Right now we require php >= 5.3 to ensure the app is able to run on old systems.
PHP Parser Version 2.0 requires at least PHP 5.4 

I can't say for sure that we will require 5.4 in order to use the parser version 2

**Comment by theofidry** [comment]
And is there a plan for newer versions? It would be quite disappointing not to be able to use it for PHP7 nor any Laravel application (they are all shipping with psysh aka tinker which uses php-parser v2).

**Comment by scaytrase** [comment]
Any updates?

**Comment by slde-robin** [comment]
Can you checkout the master ?

**Comment by scaytrase** [comment]
Looks good with php 7.1

**Comment by smoench** [comment]
@MarvinKlemp Could be closed. PhpParser has been upgraded to version 3.x
