### ISSUE TITLE
Could not find package sensiolabs-de/deprecation-detector at any version...

### ISSUE THREAD

**Issue by strauss69400** [sensiolabs-de/deprecation-detector#111]
Hi,

when i try to install this bundle, i get this error :
[InvalidArgumentException]
  Could not find package sensiolabs-de/deprecation-detector at any version for your minimum-stability (stabl
  e). Check the package spelling or your minimum-stability

What should I do?
my symfony version is 2.8.

here is a part of my composer.json :`{

`    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "stof/doctrine-extensions-bundle": "^1.2",
        "knplabs/knp-paginator-bundle": "^2.5",
        "gregwar/captcha-bundle": "^1.1",
        "sonata-project/seo-bundle": "^2.0",
        "liip/imagine-bundle": "^1.3",
        "doctrine/doctrine-fixtures-bundle": "^2.2",
        "twig/extensions": "^1.3",
        "maxmind/geoip": "^1.0",
	"suncat/mobile-detect-bundle": "0.10.*"
    },`

thank you for your help

**Comment by slde-flash** [comment]
please take a look at https://github.com/sensiolabs-de/deprecation-detector#composer 

the deprecation detector is a standalone project, better don't try to add it as a project dependency.

**Comment by strauss69400** [comment]
yes, i read the doc.i get this error when i install it with composer such as : 
"composer global require sensiolabs-de/deprecation-detector".
do I install it with "Standalone installation" ?
thanks
