### ISSUE TITLE
Add Travis Configuration

### ISSUE THREAD

**Issue by meandmymonkey** [sensiolabs-de/deprecation-detector#12]
Add a basic Travis config for supported PHP versions. As a first step, testing for the same PHP versions, cross-version testing will be added at a later stage.

**Comment by meandmymonkey** [comment]
see also #26 and #27

**Comment by MarvinKlemp** [comment]
Can I close this one ?

**Comment by meandmymonkey** [comment]
Yes, I guess... I was thinking about cross-version testing, but this is a feature for future versions, if at all. So we can close this for now, IMO.
