### ISSUE TITLE
bug detecting by-reference use?

### ISSUE THREAD

**Issue by craigh** [sensiolabs-de/deprecation-detector#122]
please see http://stackoverflow.com/questions/41198220/how-to-re-code-php-assign-by-reference-usage/41198841 for full explanation.

basically, I am getting `Using deprecated language feature assign by reference(&=) Since PHP 5.3 use normal assignment instead.`

 - [deprecation log](https://travis-ci.org/zikula/core/jobs/184641360#L875-L878)
 - [class being checked](https://github.com/zikula/core/blob/master/src/system/ThemeModule/Engine/ParameterBag.php)

I am questioning whether this error should be thrown at all.

**Comment by slde-robin** [comment]
👍 
Looks like an error in the tool.

Can you fix this ?

https://github.com/sensiolabs-de/deprecation-detector/blob/master/src/Visitor/Usage/FindLanguageDeprecations.php#L35

**Comment by slde-robin** [comment]
#123
