### ISSUE TITLE
Symmetric array destructuring results in 'Syntax error'

### ISSUE THREAD

**Issue by Blackskyliner** [sensiolabs-de/deprecation-detector#125]
When I run the deprecation detector on a codebase using PHP 7.1 which is using the new [Symmetric array destructuring](http://php.net/manual/de/migration71.new-features.php#migration71.new-features.symmetric-array-destructuring) feature I get the following error: 

> Syntax error, unexpected '=' in file /Users/ck/Documents/Work/geh-web/src/Geh/EntityBundle/Request/ParamConverter/EntityParamConverter.php

```php
<?php
[$namespaceAlias, $simpleClassName] = explode(':', 'SomeNamespace:SomeClass');
```

I don't know if it's an limitation of used php functions which results in that error, just wanted to note that it currently not works correct. 

Alternatively don't state '^7.0' in the composer.json and only add tested Version constraints.

**Comment by Blackskyliner** [comment]
After posting I realized, maybe it's an limitation of https://github.com/nikic/PHP-Parser ?

**Comment by slde-robin** [comment]
Can you test the master ?

**Comment by Blackskyliner** [comment]
Yepp, it's now working. 
I'll close the issue then.

(You'll need to update packagist reference as I had to checkout directly from github instead of using my require-dev instance of the project, as it would not update)
