### ISSUE TITLE
Display the number of files analyzed

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs-de/deprecation-detector#41]
In one of my projects I get this output:

```
...
Checked source files in 14.591 seconds, 28.5 MB memory used
```

I was expecting something like:

```
...
Checked 247 source files in 14.591 seconds, 28.5 MB memory used
```

This message is output here: https://github.com/sensiolabs-de/deprecation-detector/blob/master/src/EventListener/CommandListener.php#L57

**Comment by MarvinKlemp** [comment]
:+1:

**Comment by meandmymonkey** [comment]
BTW, couldn't this also be named something like "(Command)StatsListener", instead of the generic "CommandListener"?
