### ISSUE TITLE
Phars generated for releases should not contain dev dependencies

### ISSUE THREAD

**Issue by stof** [sensiolabs-de/deprecation-detector#52]
Your phar attached to the 0.1.0-alpha1 release (with a typo in the tag name btw) contains all dev dependencies, making it much bigger than necessary (half of the dependencies are dev ones).

You should run ``composer install --no-dev --optimize-autoloader`` before generating the phar (and then run ``composer install`` again to reinstall dev dependencies locally after the phar generation)

**Comment by MarvinKlemp** [comment]
:+1: 
Thanks my bad
