### ISSUE TITLE
Consider simplifying its use as a global tool

### ISSUE THREAD

**Issue by javiereguiluz** [sensiolabs-de/deprecation-detector#56]
First of all, thanks for publishing this cool and useful tool.

I plan to use this tool similarly to `phpunit` and `php-cs-fixer`. I've built the PHAR file and installed in the global `bin` directory. But this project could provide the PHAR already built (like other projects do) to simplify its use.

Besides, this PHAR could also provide "self-updating" feature (such as PHP-CS-Fixer, Composer, the Symfony Installer, etc.) This makes it much easier to stay up-to-date.

**Comment by slde-incal** [comment]
Yes, this is the plan. We are however focusing on completing and stabilizing the base functionality for now - but PRs for this are definitely welcome!

**Comment by MarvinKlemp** [comment]
I would love to see it integrated in the php world :)

Actually we provide a prebuild PHAR, but still an installer would be a much easier way to install the tool.
https://github.com/sensiolabs-de/deprecation-detector/releases

**Comment by WouterJ** [comment]
Why should it use a phar and not just rely on `composer global require ...`?

**Comment by javiereguiluz** [comment]
Because `composer global require` is considered "a bad practice" and even "dangerous" by some developers.
